[instructor]
name = "Tyler Shoemaker"
email = "tshoemaker@tamu.edu"
office = "LAAH 480"
hours = "TR 11:00am--12:00pm"

[course]
number = "ENGL 308"
title = "History of Literary Criticism"
section = 500
credits = 3
catalog = """
History of literary thought from antiquity to the present, including writers
such as Plato, Aristotle, 'Longinus,' Sidney, Shelley, and Dryden; analysis of
genres such as tragedy, lyric, and film; critical approaches such as new
criticism, structuralism, deconstruction, Marxism, feminism, new historicism,
and film studies.
"""
description = """
Our overarching concern will be the problem of representation: What is the
nature of representation? How does it differ from the real? What is it for? How
do we assess what a representation represents? After posing these questions in
the context of classical and renaissance texts, we will make multiple passes
through the last 150 years of critical thought, tracing the dynamics of
representation across art, language, culture, politics, psychic life, and
subjectivity.

**Content note --** Since Plato's _Republic_, literary-critical thought has
foregrounded the social role of art and criticism. In many of our readings, we
will encounter critics who explicitly tie their work to various social and
political dynamics, including those that concern race, gender, sexuality,
class, and other axes of identity and power. While students will never be
required to adopt a specific opinion with respect to these matters, you can
expect to engage with challenging ideas, encounter perspectives that may differ
from your own, and think critically about how critics envision their own place
within social and political contexts.
"""
assignments = """
Three times over the course of the semester you will write a 2-3 page **reading
response** about a text of your choosing. The purpose of these responses is to
practice the primary form of critical analysis that we do together in class:
_explanation_ and _argument_. For each response, you will select a passage and
construct an argument about the significance of this passage for the text in
which it appears. Your argument, in other words, will focus on how the passage
helps explain something about the text as a whole---what the text is about,
what it tries to do, what its internal mechanics are, where its argument works,
and where that argument might even fail.

At the end of the semester, you will complete a take-home **final exam**, which
consists of 8 multiple-choice questions and short-answer responses. You will
have one week to finish the exam. Each question will center on a key topic from
the course and present several authors who have written about it. You will
select one of these authors and explain how their work relates to the topic.

In addition to the baseline participation expectations outlined below, part of
your **participation** grade entails filling out a short poll. This poll will
ask you and your peers to vote on a final set of readings from our course
textbook, which we will cover together in the last full week of classes.
"""
prerequisites = "3 credits of literature at 200-level or above"
designation = "None"

[schedule]
year = "2026"
start = "01-12"
end = "04-28"
weekdays = "TR" 
time = "9:35--10:50am"
location = "LAAH 372"
exclude = [ 
  "01-19", "03-09", "03-10", "03-11", "03-12", "03-13", "04-03", "04-09" 
]

[[objective]]
description = """Identify and describe key themes and ideas in the history of
literary criticism"""

[[objective]]
description = """Trace the development of various critical movements and
approaches"""

[[objective]]
description = """Explain how critics develop their own interpretations and
arguments in response to other critics"""

[[objective]]
description = """Hone the skills necessary to situate one's interpretations
alongside the thoughts, opinions, ideas, and interpretations of others"""

[[objective]]
description = """Analyze critical arguments and use them to construct arguments
of one's own"""

[[book]]
title = "_The Norton Anthology of Theory and Criticism_, 3rd ed."
author = "Leitch et al"
isbn = "978-0393602951"

[[assignment]]
name = "Reading Response 1"
points = 20
due = "By 2/13"

[[assignment]]
name = "Reading Response 2"
points = 20
due = "By 3/20"

[[assignment]]
name = "Reading Response 3"
points = 20
due = "By 4/24"

[[assignment]]
name = "Final exam"
points = 30
due = "4/30"

[[assignment]]
name = "Participation"
points = 10
due = "Ongoing"

